# ~/.tmux.conf

# --- Change Prefix to Ctrl+a ---
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# --- General Settings ---
set -g status-interval 1      # Refresh tmux info on status bar (i.e. time,battery status)
set -g mouse on               # Enable mouse clicking/dragging by default
set -g base-index 1           # Start window numbering at 1 (easier to reach)
setw -g pane-base-index 1     # Start pane numbering at 1
set -g renumber-windows on    # Automatically renumber windows when one is closed
set-option -g history-limit 10000000 # History Saved lines

# --- The "Vibrant Noir" Status Bar ---
set -g status-style 'bg=default fg=#00ffff'  # Transparent bg, Cyan text
# Changed Apple logo to Manjaro logo ()
set -g status-left ' #[fg=#39ff14,bold]  #S '    
set -g status-right ' #[fg=#ebcb8b]#($HOME/.tmux/battery.sh) #[fg=#ff00ff,bold]  %H:%M:%S '  # Yellow battery, Hot Pink clock
# Active window tab (Pure Black text on Hot Pink background)
setw -g window-status-current-style 'fg=#000000 bg=#ff00ff bold'
setw -g window-status-current-format ' #I:#W '

# Inactive window tabs
setw -g window-status-style 'fg=#4d4d4d bg=default'
setw -g window-status-format ' #I:#W '

# --- Faster Switching ---
# Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# --- True Color support for tmux ---
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# --- Easier Mouse Toggle ---
# Press Prefix (Ctrl+a) then 'y' to turn mouse ON
bind y set -g mouse on \; display 'Mouse: ON (Resizing enabled)'

# Press Prefix (Ctrl+a) then 'n' to turn mouse OFF
bind n set -g mouse off \; display 'Mouse: OFF (Standard Pasting enabled)'

# Press Prefix (Ctrl+a) then 'r' to reload config
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# Enable the terminal title bar updates
set -g set-titles on

# Set the title string to the current path
# This uses a small shell snippet to replace the home path with ~
set -g set-titles-string "#(echo #{pane_current_path} | sed \"s|^$HOME|~|\")"

# ==========================================
# ===   TMUX PLUGIN MANAGER (TPM)        ===
# ==========================================

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# Plugin Configurations
set -g @continuum-restore 'on' # Auto-restore on tmux start

# Plugin Configurations
set -g @continuum-restore 'on' # Auto-restore on tmux start
set -g @continuum-save-interval '1' # Autosave every 1 minute

# Initialize TMUX plugin manager (Keep this at the very bottom!)
run '~/.tmux/plugins/tpm/tpm'
